# Example configuration entry
debug:
  update_interval: 5s

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    # fragmentation:
    #   name: "Heap Fragmentation"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
    # psram:
    #   name: "Free PSRAM"
    cpu_frequency:
      name: "CPU Frequency"

# Logger must be configured
# logger:
#   level: debug

# 
# sensor.debug: [source develesp/./wifi/include/modules/debug.yaml:13]
#   platform: debug
#   free: 
#     name: Heap Free
#   
#   This feature is only available on [<Platform.ESP8266: 'esp8266'>].
#   fragmentation: 
#     name: Heap Fragmentation
#   block: 
#     name: Heap Max Block
#   loop_time: 
#     name: Loop Time
#   
#   This option requires component psram.
#   psram: 
#     name: Free PSRAM
#   cpu_frequency: 
#     name: CPU Frequency
